# Generated by Django 4.0.2 on 2022-12-03 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlerating',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='rating_sum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
